# Autogenerated wrapper script for libflame_jll for aarch64-linux-gnu
export libflame

using libblastrampoline_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("libflame")
JLLWrappers.@declare_library_product(libflame, "libflame.so.1")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libflame,
        "lib/libflame.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
