# Autogenerated wrapper script for libflame_jll for x86_64-apple-darwin
export libflame

using libblastrampoline_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("libflame")
JLLWrappers.@declare_library_product(libflame, "@rpath/libflame.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libflame,
        "lib/libflame.1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
